export const mixedFood = [
  "Рыба",
  "Трава",
  "Орехи",
  "Водяные растения",
  "Сено",
  "Листья",
  "Фрукты (яблоки, арбузы, бананы)",
  "Огурцы",
  "Морковь",
  "Конфеты",
  "Капуста",
  "Свёкла",
  "Лук",
  "Чеснок",
  "Тыква",
  "Брокколи",
  "Мясо",
  "Цитрусовые (апельсины, лимоны, грейпфруты)",
  "Чай",
  "Картофель",
  "Грибы",
];
export const mixedFoodEng = [
  "Fish",
  "Grass",
  "Nuts",
  "Aquatic plants",
  "Hay",
  "Leaves",
  "Fruits (apples, watermelons, bananas)",
  "Cucumbers",
  "Carrots",
  "Candies",
  "Cabbage",
  "Beets",
  "Onion",
  "Garlic",
  "Pumpkin",
  "Broccoli",
  "Meat",
  "Citrus fruits (oranges, lemons, grapefruits)",
  "Tea",
  "Potatoes",
  "Mushrooms",
];
export const allowedFoods = [
  "Трава",
  "Водяные растения",
  "Сено",
  "Листья",
  "Фрукты (яблоки, арбузы, бананы)",
  "Огурцы",
  "Морковь",
  "Капуста",
  "Свёкла",
  "Тыква",
  "Брокколи",
];
export const forbiddenFoods = [
  "Мясо",
  "Рыба",
  "Цитрусовые (апельсины, лимоны, грейпфруты)",
  "Чай",
  "Картофель",
  "Грибы",
  "Конфеты",
  "Чеснок",
  "Лук",
  "Орехи",
];
export const allowedFoodsEng = [
  "Grass",
  "Aquatic plants",
  "Hay",
  "Leaves",
  "Fruits (apples, watermelons, bananas)",
  "Cucumbers",
  "Carrots",
  "Cabbage",
  "Beets",
  "Pumpkin",
  "Broccoli",
];
export const forbiddenFoodsEng = [
  "Meat",
  "Fish",
  "Citrus fruits (oranges, lemons, grapefruits)",
  "Spicy food",
  "Chocolate",
  "Candies",
  "Tea",
  "Potatoes",
  "Mushrooms",
  "Garlic",
  "Onion",
  "Nuts",
];
